name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master  # Ändere dies, wenn du einen anderen Branch verwenden möchtest
  # Optional: Trigger auch bei Tag-Erstellung
  # tags:
  #   - 'v*'
  workflow_dispatch:  # Manuelle Auslösung des Workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for advanced Docker building)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: |
          # Baue das Docker-Image unter Verwendung des Dockerfiles im "docker/"-Verzeichnis
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nextcloud:${{ github.sha }} -f .examples/dockerfiles/full/apache/Dockerfile .

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nextcloud:${{ github.sha }}
